apiVersion: v1
kind: Service
metadata:
  name: session
  labels:
    app: session
spec:
  selector:
    app: session
  ports:
    - name: http
      port: 8002
      targetPort: 8002
  type: ClusterIP
